version: '3'

services:
    server:
        build: ./backend
        expose:
            - 5000
        ports:
            - 5000:5000
        networks:
            - apiNetwork
    
    client:
        build: ./frontend
        expose:
            - 8080
        ports: 
            - 8080:80
        links: 
            - server
        depends_on:
            - server
        networks:
              - apiNetwork

networks:
  apiNetwork:
